
version: 2
sources:
  - name: PolicyStats
    database: airflow
    schema: policy_trn
    tables:
      - name: stg_pt
    quoting:
      database: true
      schema: true
      identifier: false
seeds:
  - name: etl_history
    description: "Imitating incremental load from full export. Only for training."
    config:
      column_types: 
        transactiondate: integer   
  - name: dim_transaction
    description: "List of transaction types to create DIM_TANSACTION"
    config:
      column_types:
        transaction_id: integer
        transactioncd: varchar(50)
models:
  - name: etl_log
    description: "Incremental load details"
    columns:
      - name: loaddate
        description: "Timestamp of the load start. It's a primary key."
        tests:
          - unique
          - not_null       
      - name: transactiondate
        description: "The latest Transaction Date in this load."
        tests:
          - not_null         
      - name: endloaddate
        description: "Timestamp of the load end"                 
  - name: dim_policy 
    description: "Auto policy dimension"
    columns:
      - name: policy_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: dim_coverage
    description: "Coverage dimension"
    columns:
      - name: coverage_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: dim_limit
    description: "Limits dimension"
    config:
      meta:
        surrogate_key: true
    columns:
      - name: limit_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: dim_deductible
    description: "Deductibles dimension"
    columns:
      - name: deductible_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null  
  - name: dim_vehicle
    description: "Vehicle scd2 dimension"
    columns:
      - name: vehicle_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dim_driver
    description: "Driver scd2 dimension"
    columns:
      - name: driver_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null                    

