
version: 2
sources:
  - name: PolicyStats
    database: airflow
    schema: policy_trn
    tables:
      - name: stg_pt
    quoting:
      database: true
      schema: true
      identifier: false
seeds:
  - name: orchestration_history
    description: "Imitating incremental load from full export. Only for demo/training."
    config:
      tags:
        - service    
      column_types: 
        transactiondate: integer   
  - name: dim_transaction
    description: "List of transaction types to create DIM_TANSACTION"
    config:
      tags:
        - dim    
      column_types:
        transaction_id: integer
        transactioncd: varchar(50)
models:
  - name: orchestration_log
    config:
      tags:
        - service      
    description: "Orchestration load details"
    columns:
      - name: loaddate
        description: "Timestamp of the load start. It's a primary key."
        tests:
          - unique
          - not_null       
      - name: transactiondate
        description: "The latest Transaction Date in this load."
        tests:
          - not_null         
      - name: endloaddate
        description: "Timestamp of the load end"     

  - name: dbt_log
    config:
      tags:
        - service      
    description: "DBT load details"
    columns:
      - name: startdate
        description: "Timestamp of the load start. It's a primary key."
        tests:
          - unique
          - not_null       
      - name: operation
        description: "Logged operation."
        tests:
          - not_null         
      - name: enddate
        description: "Timestamp of the load end"  

  - name: stg_driver
    config:
      tags:
        - stg      
    description: "SCD2 Driver staging view to provide logic in load_scd2 macro"

  - name: stg_vehicle
    config:
      tags:
        - stg      
    description: "SCD2 Vehicle staging view to provide logic in load_scd2 macro"    

  - name: dim_policy 
    config:
      tags:
        - dim
    description: "Auto policy dimension"
    columns:
      - name: policy_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: dim_coverage
    config:
      tags:
        - dim
    description: "Coverage dimension"
    columns:
      - name: coverage_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: dim_limit
    config:
      tags:
        - dim
      meta:
        surrogate_key: true        
    description: "Limits dimension"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - limit1
            - limit2
    columns:
      - name: limit_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: dim_deductible
    config:
      tags:
        - dim
    description: "Deductibles dimension"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - deductible1
            - deductible2    
    columns:
      - name: deductible_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null  
  - name: dim_vehicle
    config:
      tags:
        - dim
        - scd2
    description: "Vehicle scd2 dimension"
    columns:
      - name: vehicle_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dim_driver
    config:
      tags:
        - dim
        - scd2
    description: "Driver scd2 dimension"
    columns:
      - name: driver_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null           

  - name: fact_policytransaction
    config:
      tags:
        - fact
    description: "Policy Transaction Facy Table"                    

